wavetoy_serial: wavetoy_serial.c
	gcc wavetoy_serial.c -o wavetoy_serial

clean:
	-rm -f wavetoy_serial

# NOTE: To compile the OpenMP version, use 
# gcc -fopenmp wavetoy_openmp.c -o wavetoy_openmp
# will add this in the makefile in future
# To compile the MPI version, use
# mpicc wavetoy_mpi_L0.c -o wavetoy_mpi
